services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
    app:
        build:
            context: .
        image: nextjs-dev
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        env_file: .env
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        depends_on:
            - db
