version: '3.8'

services:
  web:
    build: ./
    command: gunicorn feedboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
    - 8000
    env_file:
      - .env
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data: