# Generated by Django 3.2.9 on 2021-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
