# Generated by Django 3.2.9 on 2021-12-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_status_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='colour',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
