# Generated by Django 3.2.9 on 2021-12-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='colour',
        ),
    ]
