# Generated by Django 4.0.2 on 2022-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_time_userinfo_req_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='req_method',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
