# Generated by Django 3.2.9 on 2021-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_status_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='colour',
            field=models.CharField(default='#ff6666', max_length=7),
        ),
    ]
