# Generated by Django 3.2.9 on 2021-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_status_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='colour',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
