# Generated by Django 4.0.2 on 2022-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userinfo_path_userinfo_req_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='req_method',
            field=models.CharField(default='', max_length=7),
        ),
    ]
