# Generated by Django 4.0.2 on 2022-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userinfo_path_alter_userinfo_req_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='content_type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='http_host',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='http_referer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='server_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='server_port',
            field=models.IntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='server_protocol',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
