# Generated by Django 4.0.2 on 2022-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userinfo_content_type_userinfo_http_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='http_referer',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='server_port',
            field=models.PositiveIntegerField(default=8000),
        ),
    ]
