# Generated by Django 3.2.9 on 2022-04-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220401_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.project'),
        ),
    ]
