# Generated by Django 3.2.9 on 2022-04-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.category'),
        ),
    ]
