# Generated by Django 3.2.9 on 2022-04-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_status_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.status'),
        ),
    ]
