import type { Metadata } from "next";
import SessionProvider from "@/components/context/session-provider";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/context/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/ui/header";
import { cn } from "@/lib/utils";
import { getUserSession } from "@/auth";
import "./globals.css";

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Feedboard",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getUserSession();

    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased flex flex-col gap-8 mb-16",
                    fontSans.variable
                )}
            >
                <SessionProvider session={session}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Header />
                        <main className="px-8 w-full">{children}</main>
                    </ThemeProvider>
                    <Toaster />
                </SessionProvider>
            </body>
        </html>
    );
}
